### PR TITLE
Treat bsb errors as warnings

### PR DESCRIPTION
**Pull request by cxa**
To fix this issue: https://github.com/cxa/reason-react-webpack-starter-kit/issues/1

### CODE REVIEW

**Comment by rrdelaney** [comment]
Thanks! Sorry I didn't get around to this yet, I'll merge and release a new version now.

**Comment by rrdelaney** [comment]
Published as version 1.2.1 in 7abd8b7735f2dc40635221f321dc5286c2c29a2e

**Comment by rrdelaney** [comment]
This caused some unexpected errors when running `webpack -w`. I put this behavior behind the option `errorType`. See https://github.com/rrdelaney/bs-loader#errortype

I'm going to publish 1.2.2 with the old default

**Comment by cxa** [comment]
Shouldn't call `callback` on bsb error, otherwise webpack will be terminated. Here's my workaround:

```js
const getCompiledFile = (path, callback, emitWarning) => {
  runBsb((err, res) => {
    if (err) {
      if (emitWarning) emitWarning(res)
      else return callback(err, res)
    }

    readFile(path, (err, res) => {
      if (err) {
        callback(err, err)
      } else {
        const src = transformSrc(res.toString())
        callback(null, src)
      }
    })
  })
}

module.exports = function () {
  const options = getOptions(this) || {}
  const errorType = options.errorType || 'error'
  const moduleDir = options.module || 'js'

  this.addDependency(this.resourcePath + 'i')
  const callback = this.async()
  const compiledFilePath = getJsFile(moduleDir, this.resourcePath)

  getCompiledFile(compiledFilePath, (err, res) => {
    if (err) {
      this.emitError(res)
      callback(err, null)
    } else {
      callback(null, res)
    }
  }, errorType === 'warning' ? this.emitWarning : null)
}
```

**Comment by rrdelaney** [comment]
Did this work with your kit and plain webpack watch?

**Comment by cxa** [comment]
if bsb generate error, webpack -w will stop, the same behavior as current bs-loader, otherwise its perfect.

**Comment by rrdelaney** [comment]
That seemed to work for me, published as v1.2.3

**Pull request merged**
