### PR TITLE
 update package.json git url

### PR DESCRIPTION
**Pull request by Haroenv**
from reason-scripts to bs-loader

### CODE REVIEW

**Review by rrdelaney — APPROVED** [review]
Thanks for catching this! I had meant to combine this with the reason-scripts repo a while ago, but it never happened

**Comment by Haroenv** [comment]
thanks for merging! By the way, I don’t really understand the notice in the readme, if I just have a library written in Reason, should I import .bs.js even though the files don’t exist, and run the build task together with the tests?

**Comment by rrdelaney** [comment]
@Haroenv yep! It's a more stable way of configuring everything. `bs-loader` got pretty complex due to trying to support every configuration under the sun.

**Comment by Haroenv** [comment]
okay, that makes sense. I’d prefer some way to not have to run two processes, but I guess this is the “easiest” 😄

**Pull request merged**
